---
- name: Configure Proxmox hosts
  hosts: proxmox
  gather_facts: true
  become: true
  roles:
    - proxmox
    - proxmox_storage
    - proxmox_gpu_passthrough
    - proxmox_vm_template
    - proxmox_lxc_template
    - proxmox_backup
    - opentofu_user
