---
proxmox_storage_manage: true
proxmox_storage_disks:
  - device: /dev/sdb1
    vg_name: vmstore
    storage_id: local-vmstore
    content: images,rootdir

proxmox_gpu_passthrough_manage: true
proxmox_gpu_passthrough_iommu_vendor: intel
proxmox_gpu_passthrough_pci_ids:
  - "10de:1c03"
