---
all:
  children:
    proxmox:
      hosts:
        pve:
          ansible_host: "{{ pve_host }}"
          ansible_python_interpreter: /usr/bin/python3
    linux:
      hosts:
        # VM for testing ansible iac setup, remove once config is stable
        ubuntu:
          ansible_host: "{{ ubuntu_host }}"
          ansible_python_interpreter: /usr/bin/python3
