---
all:
  children:
    proxmox:
      hosts:
        pve:
          ansible_host: "{{ pve_host }}"
          ansible_python_interpreter: /usr/bin/python3
    linux:
      hosts: {}
    dns:
      hosts:
        technitium:
          ansible_host: "{{ technitium_host }}"
          ansible_python_interpreter: /usr/bin/python3
    reverse_proxy:
      hosts:
        traefik:
          ansible_host: "{{ traefik_host }}"
          ansible_python_interpreter: /usr/bin/python3
    gpu:
      hosts:
        gpu-box:
          ansible_host: "{{ gpu_host }}"
          ansible_python_interpreter: /usr/bin/python3
    monitoring:
      hosts:
        palantir:
          ansible_host: "{{ palantir_host }}"
          ansible_python_interpreter: /usr/bin/python3
    container_management:
      hosts:
        portainer:
          ansible_host: "{{ portainer_host }}"
          ansible_python_interpreter: /usr/bin/python3
    opnsense:
      hosts:
        router:
          ansible_connection: local
          ansible_python_interpreter: "{{ opnsense_ansible_python_interpreter }}"
