---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: homepage-domain
  namespace: homepage
spec:
  encryptedData:
    domain: AgA1NHm748m656dPp/kZNDVI3148wsiiBbvWUAlZwYGz8CWaH66Qz0ePETrag1xwTTfwFX6jcwqsPDcH0ry6g4nKlaVU40jpXXBRRax0T66PwN67hyUa06R5CPQ1LiQLR+lENaZdZB7mo0Dj3HtGbZdbtvPiFQa3JbYDyYDj1m4wbxvmKiCBiEZFm2fQ+OS/sYmS8DZSUbRUnVBa+gpWHvgOm2pQliMrzV6eEqdy805AlxK6p3O/LqBZ+dEtOJM4BLALCJFajast4XI8pJIG+JMySHpDZR4h8knfECAyDdUast/sIss6nIkeqXWpJPV7Dkj3yOMaceHEPGmGkoRCODd8buQy5yxwQ3jmGdr+FlYSmh3vhgJv8wJK+shUSQKqO7i8Hm3OL3am8+WUJRG9Q2yH9KCH2yiOdqOtZ7eK2cjE0kNe3QBHqaKoWw4UX0rC5zEtZG9i0/rlDTKTJGGuoqvbpeeQb1e6GPVAFFVX/lx7zntPznIRVwiv145Vhyw68w7aQE/bqu+JKHXk7PiPtz4QUKiQPKYrqWNLpSJsF7Ex6EDYAdKj9rEL0uCel5crgetp90Hx0O2ZKZdXH3pSmfBY9qkxfs8Xnd+ojn/JJtEQLZsgU3tR6VlEiSzxcl4yuZ80lrGhabwyuYPGW0uxKtKMxHL06ef56diMWj6XzmdTeZaZzk4jVKyPDWVZn17RFBSkEaGv6AEPqqeR4jLJzmSDzw==
  template:
    metadata:
      name: homepage-domain
      namespace: homepage
