---
technitium_dns_records:
  - name: "technitium.{{ local_domain }}"
    ip: "{{ technitium_host }}"
  - name: "router.{{ local_domain }}"
    ip: "{{ opnsense_host }}"
  - name: "traefik.{{ local_domain }}"
    ip: "{{ traefik_host }}"
  - name: "pve.{{ local_domain }}"
    ip: "{{ traefik_host }}"
  - name: "gpu-box.{{ local_domain }}"
    ip: "{{ gpu_host }}"
  - name: "palantir.{{ local_domain }}"
    ip: "{{ palantir_host }}"
  - name: "portainer.{{ local_domain }}"
    ip: "{{ traefik_host }}"
  - name: "jellyfin.{{ local_domain }}"
    ip: "{{ traefik_host }}"
  - name: "ollama.{{ local_domain }}"
    ip: "{{ traefik_host }}"
  - name: "openwebui.{{ local_domain }}"
    ip: "{{ traefik_host }}"
  - name: "grafana.{{ local_domain }}"
    ip: "{{ traefik_host }}"
  - name: "prometheus.{{ local_domain }}"
    ip: "{{ traefik_host }}"
  - name: "argocd.{{ local_domain }}"
    ip: "{{ traefik_host }}"
  - name: "gondor.{{ local_domain }}"
    ip: "{{ gondor_host }}"
  - name: "rohan.{{ local_domain }}"
    ip: "{{ rohan_host }}"
  - name: "shire.{{ local_domain }}"
    ip: "{{ shire_host }}"
